"""
Utilities - Helper functions for changelog management.

Provides utility functions for formatting, export, and file operations.
"""

import json
from pathlib import Path
from typing import List, Optional
from .types import (
    ChangelogEntry,
    VersionTableEntry,
    RevisionReport,
    Version,
)


class MarkdownFormatter:
    """Format changelog data as Markdown."""
    
    @staticmethod
    def format_entry(entry: ChangelogEntry) -> str:
        """
        Format a changelog entry as Markdown.
        
        Args:
            entry: ChangelogEntry to format
            
        Returns:
            Markdown-formatted string
        """
        lines = [
            f"## Entry: {entry.entry_id}",
            "",
            f"- **Date**: {entry.date.isoformat()}",
            f"- **Module**: {entry.module}",
            f"- **Version**: {entry.version_from} → {entry.version_to}",
            f"- **Change Type**: {entry.change_type.value}",
            f"- **Summary**: {entry.summary}",
            f"- **Rationale**: {entry.rationale}",
            f"- **Files Modified**: {', '.join(entry.files_modified)}",
            f"- **Author**: {entry.author}",
            f"- **Reviewer**: {entry.reviewer}",
        ]
        
        if entry.related_entries:
            lines.append(f"- **Related Entries**: {', '.join(entry.related_entries)}")
        
        if entry.external_references:
            lines.append(f"- **External References**: {', '.join(entry.external_references)}")
        
        if entry.impact_assessment:
            lines.append(f"- **Impact Assessment**: {entry.impact_assessment}")
        
        if entry.migration_notes:
            lines.append(f"- **Migration Notes**: {entry.migration_notes}")
        
        if entry.tags:
            lines.append(f"- **Tags**: {', '.join(entry.tags)}")
        
        lines.append("")
        return "\n".join(lines)
    
    @staticmethod
    def format_version_table(entries: List[VersionTableEntry]) -> str:
        """
        Format version table entries as Markdown table.
        
        Args:
            entries: List of VersionTableEntry objects
            
        Returns:
            Markdown table string
        """
        lines = [
            "| Module | Current Version | Status | Freeze Date | Supersedes |",
            "|--------|-----------------|--------|-------------|------------|",
        ]
        
        for entry in entries:
            freeze_date = entry.freeze_date.isoformat() if entry.freeze_date else "—"
            supersedes = str(entry.supersedes) if entry.supersedes else "—"
            
            lines.append(
                f"| {entry.module_id} | {entry.current_version} | "
                f"{entry.status.value} | {freeze_date} | {supersedes} |"
            )
        
        return "\n".join(lines)
    
    @staticmethod
    def format_revision_report(report: RevisionReport) -> str:
        """
        Format a complete revision report as Markdown.
        
        Args:
            report: RevisionReport to format
            
        Returns:
            Markdown-formatted report
        """
        lines = [
            f"# Revision Report: {report.metadata.report_id}",
            "",
            "## Report Metadata",
            "",
            f"- **Report ID**: {report.metadata.report_id}",
            f"- **Generation Date**: {report.metadata.generation_date.isoformat()}",
            f"- **Reporting Period**: {report.metadata.reporting_period_start.isoformat()} to {report.metadata.reporting_period_end.isoformat()}",
            f"- **Generated By**: {report.metadata.generated_by}",
            "",
            "## Summary Statistics",
            "",
            f"- **Total Changelog Entries**: {report.summary.total_entries}",
            f"- **MAJOR Changes**: {report.summary.count_by_type.get('MAJOR', 0)}",
            f"- **MINOR Changes**: {report.summary.count_by_type.get('MINOR', 0)}",
            f"- **PATCH Changes**: {report.summary.count_by_type.get('PATCH', 0)}",
            f"- **Modules Updated**: {', '.join(report.summary.modules_updated) if report.summary.modules_updated else 'None'}",
            f"- **Contributing Authors**: {', '.join(report.summary.authors_contributing) if report.summary.authors_contributing else 'None'}",
            "",
            "## Detailed Entries",
            "",
        ]
        
        for entry in report.detailed_entries:
            lines.append(MarkdownFormatter.format_entry(entry))
        
        if report.outstanding_issues:
            lines.extend([
                "## Outstanding Issues",
                "",
            ])
            for issue in report.outstanding_issues:
                lines.append(f"- {issue}")
        
        return "\n".join(lines)


class FileSystemHelper:
    """Helper for file system operations."""
    
    @staticmethod
    def ensure_directory(path: Path) -> None:
        """
        Ensure directory exists, creating it if necessary.
        
        Args:
            path: Directory path
        """
        path.mkdir(parents=True, exist_ok=True)
    
    @staticmethod
    def write_json(path: Path, data: dict) -> None:
        """
        Write data to JSON file.
        
        Args:
            path: File path
            data: Dictionary to serialize
        """
        with open(path, 'w', encoding='utf-8') as f:
            json.dump(data, f, indent=2, ensure_ascii=False, default=str)
    
    @staticmethod
    def read_json(path: Path) -> dict:
        """
        Read JSON file.
        
        Args:
            path: File path
            
        Returns:
            Deserialized dictionary
        """
        with open(path, 'r', encoding='utf-8') as f:
            return json.load(f)
    
    @staticmethod
    def write_text(path: Path, content: str) -> None:
        """
        Write text content to file.
        
        Args:
            path: File path
            content: Text content
        """
        with open(path, 'w', encoding='utf-8') as f:
            f.write(content)


class VersionHelper:
    """Helper functions for version operations."""
    
    @staticmethod
    def parse_version_constraint(constraint: str, target_version: Version) -> bool:
        """
        Check if a version satisfies a constraint.
        
        Args:
            constraint: Version constraint string (e.g., ">=1.0.0", "==1.2.3")
            target_version: Version to check
            
        Returns:
            True if version satisfies constraint
        """
        constraint = constraint.strip()
        
        if constraint.startswith(">="):
            required = Version.from_string(constraint[2:].strip())
            return (target_version.major > required.major or
                    (target_version.major == required.major and target_version.minor > required.minor) or
                    (target_version.major == required.major and target_version.minor == required.minor and
                     target_version.patch >= required.patch))
        
        elif constraint.startswith("=="):
            required = Version.from_string(constraint[2:].strip())
            return str(target_version) == str(required)
        
        elif constraint.startswith(">"):
            required = Version.from_string(constraint[1:].strip())
            return (target_version.major > required.major or
                    (target_version.major == required.major and target_version.minor > required.minor) or
                    (target_version.major == required.major and target_version.minor == required.minor and
                     target_version.patch > required.patch))
        
        elif constraint.startswith("<="):
            required = Version.from_string(constraint[2:].strip())
            return (target_version.major < required.major or
                    (target_version.major == required.major and target_version.minor < required.minor) or
                    (target_version.major == required.major and target_version.minor == required.minor and
                     target_version.patch <= required.patch))
        
        elif constraint.startswith("<"):
            required = Version.from_string(constraint[1:].strip())
            return (target_version.major < required.major or
                    (target_version.major == required.major and target_version.minor < required.minor) or
                    (target_version.major == required.major and target_version.minor == required.minor and
                     target_version.patch < required.patch))
        
        else:
            # Assume exact match if no operator
            required = Version.from_string(constraint)
            return str(target_version) == str(required)
    
    @staticmethod
    def compare_versions(v1: Version, v2: Version) -> int:
        """
        Compare two versions.
        
        Args:
            v1: First version
            v2: Second version
            
        Returns:
            -1 if v1 < v2, 0 if v1 == v2, 1 if v1 > v2
        """
        if v1.major != v2.major:
            return -1 if v1.major < v2.major else 1
        if v1.minor != v2.minor:
            return -1 if v1.minor < v2.minor else 1
        if v1.patch != v2.patch:
            return -1 if v1.patch < v2.patch else 1
        return 0
